IncludeScript("base_id");

POINTS_PER_CAPTURE = 10
POINTS_PER_PERIOD = 2
PERIOD_TIME = 60
NUM_PHASES = 4
INITIAL_ROUND_DELAY = 45
ROUND_DELAY = 20
TEAM_SWITCH_DELAY = 5
FLAG_RETURN_TIME = 60

SNIPER_LIMIT = 1;

